from dotenv import dotenv_values
config = dotenv_values("config.env")

datadir=config["datadir"]
resultsdir=config["resultsdir"]
scriptsdir=config["scriptsdir"]

onstart:
    print("##### Running minimal snakemake pipeline #####")

rule all:
    input:
        f"{resultsdir}/output.txt"

include: "rules/example_rule.smk"


