datadir=config["paths"]["data"]
resultsdir=config["paths"]["results"]

onstart:
    print("##### Running minimal snakemake pipeline #####")

rule all:
    input:
        f"{resultsdir}/output.txt"

include: "rules/example_rule.smk"


