paths:
    data: &pathdata '/tmp/snakemake-example-methylseq-data'
    results: 'example-results'

parameters:
    assembly: 'hg19'

use-apptainer: True
apptainer-args: '-B *pathdata'

executor: slurm
cluster:
  export USER=$(whoami) &&
  export ACCOUNT_ID=$(sacctmgr show user withassoc format=account where user=$USER | grep '[0-9]' | head -n1) &&
  sbatch
    --partition={resources.partition}
    --account=$ACCOUNT_ID
    --nodes={resources.nodes}
    --ntasks-per-node={resources.ntasks_per_node}
    --cpus-per-task={resources.ntasks_per_node}
    --time={resources.time}
    --cpus-per-task={threads}
    --mem={resources.mem}
    --job-name={rule}-{wildcards}
    --output=slurm_log_{rule}_%j.out
default-resources:
  - time='01:00:00'
  - partition=mrcieu
  - mem='1G'
  - ntasks_per_node=1
  - nodes=1
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 10
jobs: 10
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
