datadir = config['paths']['data']
genomedir = config['paths']['data']
fastqdir = f"{datadir}/fastq"
outdir = config['paths']['results']

assembly = config['parameters']['assembly']

onstart:
    print("##### Running example snakemake pipeline #####")

rule all:
    input:
        f"{outdir}/matrix/sum.csv"

include: "rules/retrieve_genome.smk"
include: "rules/retrieve_data.smk"
include: "rules/trim_reads.smk"
include: "rules/meth_counts.smk"
include: "rules/meth_matrix.smk"
include: "rules/meth_sum.smk"




